config/routes.rb
Rails.application.routes.draw do

  root to: "homes#index"
  
  get "about",to: "abouts#index"
  get "contact", to: "contacts#index"
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get "signup",to: "users#new"
  get "detail",to: "users#show"
  
  get 'rankings/place', to: 'places#rank'
  
  resources :users, only: [:new, :create, :show]
  
  resources :reports, only: [:new, :create, :destroy]
  resources :places, only: [:show, :index, :create]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord
    
    validates :area, presence: :true, uniqueness: true
    validates :detail, presence: :true, uniqueness: true
    
    has_many :reports
    
end

        

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  belongs_to :place,optional: true
  
  validates :content, presence: true, length: { maximum: 255 }
  validates :date, presence: true
  validates :people, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email.downcase! }
    validates :name, presence: true, length: { maximum:50 } 
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
    validates :password_digest, presence: true
    
    has_secure_password
    
    has_many :reports
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  private
  
    def require_user_logged_in
     unless logged_in?
       redirect_to login_url
     end
    end
    
    def counts(user)
      @count_reports = user.reports.count
    end

    def counts(place)
      @counts_reports = place.reports.count
    end
    
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @reports = Report.order(created_at: :desc).page(params[:page]).per(10)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  
  def index
    @places = Place.all
  end
  
  def show
    @place = Place.find(params[:id])
    @reports = @place.reports.order('created_at DESC').page(params[:page])
    counts(@place)
  end
  
  def create
  end
  
  def rank
    Report.order(people: :desc).pluck(:people)
    Report.order(people: :desc).pluck(:place_id)
    ranking_ids = Report.order(people: :desc).pluck(:place_id)
    @places = Place.find(ranking_ids)
    @people_total = Report.sum(:people)
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]
  
  
  def new
    @report = Report.new
  end
  
  def create
    @report = current_user.reports.build(report_params)
    if @report.save
      flash[:success] = "感染報告を投稿しました。"
      redirect_to root_url
    else
      flash.now[:danger] = '感染報告が投稿されませんでした'
      render :new
    end
  end

  def destroy
    @report.destroy
    flash[:warning] = '感染報告を削除しました。'
    redirect_back(fallback_location: user_path(current_user))
  end
  
  private
  
  def report_params
    params.require(:report).permit(:content, :date , :people, :place_id)
  end
  
  def correct_user
    @report = current_user.reports.find_by(id: params[:id])
    unless @report
      redirect_to root_url
    end
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil;
    flash[:success] = "ログアウトしました。"
    redirect_to root_url
  end
  
   private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show]
  
  def index
    @user = User.find(params[:id])
  end
  
  def show
    @user = User.find(params[:id])
    @reports = @user.reports.order('created_at DESC').page(params[:page])
    counts(@user)
  end

  def new
    @user=User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=mp"
  end
end

app/views/abouts/index.html.erb
<div id=""
<div class="well well-sm" style="background-color:#809ece"><b>インフルエンザの特徴と症状</b></div>

<p>&nbsp;&nbsp;インフルエンザは普通の風邪とは異なり突然38度以上の「高熱」と関節痛や筋肉痛、頭痛などの他に全身の倦怠感、食欲不振などの
呼吸器だけでない全身症状が強く現れます。合併症として気管支炎、中耳炎、肺炎などもみられます。より重大な合併症には急性脳症（インフルエンザ脳症）
や重症肺炎などがあり重症化する恐れや死亡に至る恐れもあります。<br>

&nbsp;&nbsp;インフルエンザウイルスに感染した場合、約1〜3日の潜伏期間の後インフルエンザを発症します。
発症後は上記の症状が約1〜3日強く現れ通常は約10日前後で症状が落ち着き治癒します。</p>

<div class="well well-sm" style="background-color:#809ece"><b>ハイリスクグループとは</b></div>
<p>&nbsp;&nbsp;次のような方はハイリスクグループに属し重症化しやすい恐れがあります。</p>
  <ul>
    <li>高齢（65歳以上）</li>
    <li>小児（5歳未満）</li>
    <li>妊娠中</li>
    <li>肥満</li>
    <li>基礎疾患がある</li>
      <ul>
        <li>慢性呼吸器疾患（喘息、慢性閉塞性肺疾患など）</li>
        <li>慢性心疾患（先天性心疾患、冠動脈疾患など）</li>
        <li>代謝性疾患（糖尿病など）</li>
        <li>腎機能障害</li>
        <li>免疫機能不全（ステロイド内服、T細胞性免疫不全など）</li>
      </ul>
  </ul>
  
<div class="well well-sm" style="background-color:#809ece"><b>インフルエンザの予防法</b></div>
<p><div style="margin-bottom:30px">&nbsp;&nbsp;インフルエンザの流行は主に冬で地域や学校、会社などで起こります。ワクチンの予防接種をすると、インフルエンザウイルスの交代を
作らせることができる。その年に流行するインフルエンザは毎年予想され、予防接種のためのワクチンが作られます。インフルエンザウイルスの感染を
完全に予防することはできませんが、インフルエンザにかかる人や、重症化して入院する人を減らせます。</p></div>

<b><div style="font-size: 15px; border-left: solid 3px #809ece;">日常の中での予防法</div></b>
<p>&nbsp;&nbsp;日常生活でインフルエンザを予防することも大切です。<br>
通常のインフルエンザウイルスや新型インフルエンザウイルスの感染は、せきやくしゃみによる飛沫や接触によってウイルスが体内に入ることで起こります。
そこで、普段からウイルスが体内に入るのを防ぐようにしましょう。</p>
<ul>
  <li><b>飛沫感染</b></li>
    <p><div style="font-size:13px">感染者の咳、くしゃみなどにより発生した飛沫を吸い込む。</div></p>
  <li><b>接触感染</b></li>
    <p><div style="font-size:13px; margin-bottom:15px">感染者が触った物体に直接触り、そのまま目や鼻、口を触る</div></p>
</ul>

<p><div style="font-size:15px; border-left: solid 3px #809ece;"><b>予防法</b></div></p>
  <div style="margin-bottom:20px"><ul>
    <li>普段から健康管理をし、十分な栄養の食事と十分な睡眠を心がけ抵抗力を高めておきましょう。<br>&nbsp;</li>
    <li>人が多く集まる場所から帰ってきたときは手洗いをするよう心がけましょう。<br>&nbsp;</li>
    <li>アルコールを含んだ消毒液などで手を消毒するのも効果的です。</li>
  </ul></div>
  
  <pre> インフルエンザをしっかり予防して、かからないように気をつけましょう。
ただし、きちんと予防をしていてもインフルエンザにかかってしまうことがあります。
早期治療が大切ですから、インフルエンザが疑われるときはできるだけ早く医療機関で診察を受けましょう。</pre>

app/views/contacts/index.html.erb
<div style="margin-bottom:20px"><h2>CONTACT</h2></div>
  <h4 style="margin-bottom:20px">[CREATOR詳細]</h4>
    <div style="margin-bottom:20px"><img src="/images/me.jpg" alt="misa's_image"></div>
    <p>NAME : Misaki.T</p>
    <p>AGE : 21</p>
    <p>PROFESSION : STUDENT</p>
    
    <p>何かご意見ご要望などがあれば下記からお寄せください。</p>
      <p><a href="mailto:m0i2s2a4@icloud.com">>>お問い合わせ</a></p>

    

app/views/homes/index.html.erb
<h2 style="margin-bottom:40px;"><b>愛知県インフルエンザ感染状況サイト</b></h2>

<div style="font-size:18px; border-left: solid 3px #809ece; margin-bottom:20px;"><b>利用方法</b></div>
<p style="margin-bottom:20px;">この「InfluectionMap」は愛知県限定のインフルエンザ感染報告投稿サイトとなっています。このアプリの名前の由来はインフルエンザの「Influenza」と感染を意味する「Infection」を表したアプリケーションです。身近なインフルエンザの感染状況を共有しタイムリーな感染状況を知ることで少しでもインフルエンザの恐怖と感染力の高さを再認識しましょう。感染者の減少や尊い命を救う力に少しでもなることができればという思いの込もったものになっています。是非、会員登録を済ませ感染報告をお寄せください。</p>

<h2 style="margin-bottom:20px;">TIMELINE</h2>

<img src="/images/Aichi.jpg" alt="Aichi's_Map">

<p style="font-size:18px; border-left: solid 3px #809ece; margin-bottom:20px;"><b>愛知県内の現在のインフルエンザ感染報告の一覧です。</b></p>



<table class="table table-bordered">
    <thead>
        <tr class="info">
            <th class="text-center col-md-1">日付</th>
            <th class="text-center col-md-2">地域</th>
            <th class="text-center col-md-1">感染人数</th>
            <th class="text-center col-md-4">コメント</th>
            <th class="text-center col-md-1"></th>
        </tr>
    </thead>
    <tbody>
    	<% @reports.each do |report| %>
    		<tr>
    			<td><%= report.date %></td>
    			<td><%= report.place.area %></td>
    			<td><%= report.people %> 人</td>
    			<td><%= report.content %></td>
    			<td>
    				<div>
    					<% if current_user == report.user %>
            		<%= link_to "Delete", report, method: :delete, data: { confirm: "削除してもよろしいですか？" }, class: 'btn btn-danger btn-xs' %>
          		<% end %>
    				</div>
    			</td>
    		</tr>
    	<% end %>
    </tbody>
</table>

  	

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-static-top" style="background-color:#000080">
    <div class="container">
      <div class="navbar-header">
        <h2 class="navbar-text" style="color:#ffffff">INFLUECTION MAP</h2>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse navbar-right">
        <% if logged_in? %>
          <button type="button" class="btn btn-default btn-lg navbar-btn"><%= link_to "LOGOUT",logout_path,method: :delete %></button>
        <% else %>
          <button type="button" class="btn btn-default btn-lg navbar-btn"><%= link_to "SIGNUP",signup_path %></button>
          <button type="button" class="btn btn-default btn-lg navbar-btn"><%= link_to "LOGIN",login_path %></button>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Influection Map</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
    <%= render 'layouts/flash_messages' %>
    <div class="row" style="padding:15px 0 0 0">
        <div class="col-md-2">
            <div class="panel panel-default">
                <div class="panel-heading" style="background-color:#b0c4de">MENU</div>
                
                <ul class="nav nav-pills nav-stacked">
                  
                    <li><%= link_to " HOME", root_path, class: "glyphicon glyphicon-home" %></li>
                    
                    <% if logged_in? %>
                    <li><%= link_to " REPORT", new_report_path, class: "glyphicon glyphicon-pencil" %></li>
                    <% else %>
                    <li><%= link_to " REPORT ", signup_path,class: "glyphicon glyphicon-pencil" %></li>
                    <% end %>
      
                    <li><%= link_to " PLACE ", places_path,class: "glyphicon glyphicon-map-marker" %></li>
                    
                    <li><%= link_to " RANKING ", rankings_place_path,class: "glyphicon glyphicon-signal" %></li>
                    
                    <% if logged_in? %>
                    <li><%= link_to " USER ", user_path(current_user),class: "glyphicon glyphicon-user" %></li>
                    <% else %>
                    <li><%= link_to " USER ", signup_path,class: "glyphicon glyphicon-user" %></li>
                    <% end %>
                    
                    <li><%= link_to " ABOUT ", about_path, class: "glyphicon glyphicon-info-sign" %></li>
                    
                    <li><%= link_to " CONTACT ", contact_path, class: "glyphicon glyphicon-envelope" %></li>
                    
                </ul> 
        
            </div>
        </div>
        
        <div class="col-md-10">
          
          <%= yield %>
          
        </div>
    </div>
  </div>
  
    
      <footer>
        <small>&copy; 2019 Infuluection Map.</small>
      </footer>
    
  </body>
</html>

app/views/places/index.html.erb
<h1 style="margin-bottom:40px"><b>感染地域詳細</b></h1>

<p style="margin-bottom:20px; border-left: solid 3px #809ece;">選択地域のインフルエンザ感染報告ページに進みます。</p>

<img src="/images/Aichi.jpg" alt="Aichi's_Map">

<table class="table table-bordered">
    <thead>
        <tr class="info">
            <th class="text-center col-md-3">地域</th>
            <th class="text-center col-md-9">該当地域</th>
        </tr>
    </thead>
    
  <tbody>
  <% @places.each do |place| %>
  <tr>
    <td><%= link_to place.area, place_path(place) %></td>
    <td><%= place.detail %></td>
  <% end %>
  </tr>
</tbody>
</table>

app/views/places/rank.html.erb
<h1 style="margin-bottom : 50px;"><b>インフルエンザ感染注意ランキング</b></h1>

<img src="/images/Aichi.jpg" alt="Aichi's_Map">

<h4 style = "margin-bottom:20px; border-left : solid 3px #809ece;">愛知県内の合計感染人数：<%= @people_total %>人</h4>

<h5 style="border-left: solid 3px #809ece; margin-bottom:20px;">感染注意ランキング上位地域にお住いの方に限らず予防を忘れずに。</h5>

<div style="margin-bottom:20px;"><%= link_to '>>予防法は？', about_path %></div>


<ol>
  <% @places.each do |place| %>
  <h4><li><%= place.area %> : <%= place.reports.sum(:people) %>人</li></h4>
  <% end %>
</ol>

app/views/places/show.html.erb
<h1 style="margin-bottom:40px"><%= @place.area %>の感染報告一覧</h1>

<h3 style="border-left: solid 5px #809ece;"> 感染報告数：<%= @counts_reports %></h3>
<p style="margin-bottom:40px;"><%= link_to "感染ランキングを見る",rankings_place_path %></p>

<%= render "reports/area_reports", reports: @reports %>



  <div style="float:right;">
    <p style = "margin-bottom:5px;"><%= link_to "=>地域一覧に戻る",places_path %></p>
    <p style = "margin-bottom:5px;"><%= link_to "=>感染報告を登録する",new_report_path %></p>
    <p style = "margin-bottom:5px;"><%= link_to "=>感染報告一覧に戻る",root_path %></p>
  </div>

app/views/reports/_area_reports.html.erb
<table class="table table-bordered">
    <thead>
        <tr class="info">
            <th class="text-center col-xs-1">日付</th>
            <th class="text-center col-xs-1">感染人数</th>
            <th class="text-center col-xs-4">コメント</th>
            <th class="text-center col-xs-1"></th>
        </tr>
    </thead>
    <tbody>
    	<% reports.each do |report| %>
    		<tr>
    			<td><%= report.date %></td>
    			<td><%= report.people %> 人</td>
    			<td><%= report.content %></td>
    			<td>
    				<div>
    					<% if current_user == report.user %>
            		<%= link_to "Delete", report, method: :delete, data: { confirm: "削除してもよろしいですか？" }, class: 'btn btn-danger btn-xs' %>
          		<% end %>
    				</div>
    			</td>
    		</tr>
    	<% end %>
    </tbody>
</table>

app/views/reports/_reports.html.erb
<table class="table table-bordered">
    <thead>
        <tr class="info">
            <th class="text-center col-xs-1">日付</th>
            <th class="text-center col-xs-2">地域</th>
            <th class="text-center col-xs-1">感染人数</th>
            <th class="text-center col-xs-4">コメント</th>
            <th class="text-center col-xs-1"></th>
        </tr>
    </thead>
    <tbody>
    	<% reports.each do |report| %>
    		<tr>
    			<td><%= report.date %></td>
    			<td><%= report.place.area %></td>
    			<td><%= report.people %> 人</td>
    			<td><%= report.content %></td>
    			<td>
    				<div>
    					<% if current_user == report.user %>
            		<%= link_to "Delete", report, method: :delete, data: { confirm: "削除してもよろしいですか？" }, class: 'btn btn-danger btn-xs' %>
          		<% end %>
    				</div>
    			</td>
    		</tr>
    	<% end %>
    </tbody>
</table>

app/views/reports/new.html.erb
<% if logged_in? %>
  <div class="container col-md-9">
    <div class="panel panel-primary">
      <div class="panel-heading">感染報告フォーム</div>
        <div class="panel-body">
            <%= form_for(@report) do |f| %>
              
              <div class="form-group ">
                
              <div style="margin-bottom:20px">
                <%= f.label :date, '感染日' %>
                <%= f.date_select( 
                  :date,
                  use_month_numbers: true,
                  start_year: Time.now.year,
                  end_year: (Time.now.year+20),
                  default: Date.new(Time.now.year, Time.now.month, Time.now.day)) %>
              </div>
              
              <div style = "margin-bottom:20px">
                <%= f.label :place_id, '感染地域' %>
                <%= f.collection_select :place_id, Place.all, :id, :area, :include_blank => true %>
              </div>
              
              
                
              <div style="margin-bottom:20px">
                <%= f.label :people, '人数' %>
                <%= f.select :people , [ ["1","1"],["2","2"],["3","3"],["4","4"],["5","5"],["6","6"],["7","7"],["8","8"],["9","9"],["10","10"],["11","11"] ,["12","12"] ,["13","13"] ,["14","14"]  ] , :selected=>@report.people, rows: 2 %>
                </div>
                
              <div style="margin-bottom:20px">
                <%= f.label :content, 'コメント' %>
                <%= f.text_area :content, class: 'form-control', rows: 7 %>
              </div>
              </div>
        
          <div style="margin-bottom:20px">
            <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
          </div>
          
            <div class="text-center">
              <%= link_to '一覧に戻る', root_path %>
            </div>
          
          
        <% end %>
      </div>
    </div>
  </div>
<% else %>
  redirect_to root_url
<% end %>

app/views/users/new.html.erb
<div class="row">
  <div class="col-xs-offset-2 col-xs-8">
    <div class="panel panel-default">
      <div class="panel-heading"><b>会員登録を完了させて下さい。</b></div>
      <div class="panel-body">
        <%= form_for(@user) do |f| %>
          <div class="form-group">
            <%= f.label :name, '名前' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :email, 'メールアドレス' %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password, 'パスワード' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password_confirmation, 'パスワード（確認）' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

          <div class="text-center">
            <%= f.submit '登録する', class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="text-center"><%= link_to "会員登録がお済みの方はこちらからログイン",login_path %></div>

app/views/users/show.html.erb
<div class="panel">
  <aside class="col-xs-3">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
  </aside>
  <div class="col-xs-9">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %> My感染報告 <span class="badge"><%= @count_reports %></span><% end %></li>
      
    </ul>
    <%= render 'reports/reports', reports: @reports %>
   </div>
</div>